name: Spiral in green
favicon: null
layout_spectrum: 0.9155253008939326
typography_spectrum: 0.686947054695338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6975767838303
  lightness: 0.3905206830240786
  saturation: 0.23484820360317826
  rhythmicContrast: 0.4172968096099794
purpose: []
